apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: ocp-ci-analysis
  name: ocp-ci-analysis
spec:
  schedule: "0 0 1 * *"
  concurrencyPolicy: "Replace"
  workflowSpec:
    workflowTemplateRef:
      name: ocp-ci-analysis
