apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: failure-classifier-sklearn
spec:
  name: failure-classifier-model
  predictors:
  - graph:
      children: []
      implementation: SKLEARN_SERVER
      modelUri: s3://opf-datacatalog/failure-classifier/classifier
      envSecretRefName: seldon-init-container-secret
      name: classifier
      parameters:
        - name: method
          type: STRING
          value: predict
    name: default
    replicas: 1
