# We run this workflow on the base ocp-ci-analysis container image which contains dependencies neccesary to run these notebooks 
name: Predict Time to Merge

# Controls when the workflow will run
on:

  workflow_dispatch:
  pull_request:

jobs:
  pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: quay.io/aicoe/ocp-ci-analysis

    steps:
      - name: Predict Time to Merge
        uses: redhat-et/time-to-merge-tool@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.client_payload.AWS_ACCESS_KEY_ID  || secrets.AWS_ACCESS_KEY_ID}}
          GITHUB_REPO: ${{ github.event.client_payload.REPO || secrets.REPO }}
          GITHUB_ORG: ${{ github.event.client_payload.ORG || secrets.ORG }}
          S3_ENDPOINT_URL: ${{ github.event.client_payload.S3_ENDPOINT_URL || secrets.S3_ENDPOINT_URL }}
          S3_BUCKET: ${{ github.event.client_payload.S3_BUCKET || secrets.S3_BUCKET }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.client_payload.AWS_SECRET_ACCESS_KEY || secrets.AWS_SECRET_ACCESS_KEY }}
          CEPH_BUCKET: ${{ github.event.client_payload.S3_BUCKET || secrets.S3_BUCKET }}
          CEPH_BUCKET_PREFIX: ${{ github.event.client_payload.PREFIX|| secrets.CEPH_BUCKET_PREFIX }}
          CEPH_KEY_ID: ${{ github.event.client_payload.AWS_ACCESS_KEY_ID  || secrets.AWS_ACCESS_KEY_ID }}
          CEPH_SECRET_KEY: ${{ github.event.client_payload.AWS_SECRET_ACCESS_KEY || secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          # Setting mode by default as 0, this will only run inference mode and if defined as 1 will train and run inference.
          MODE: 0
          REMOTE: 1
          ACTION: 1